#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from boring_tasks
import boring_tasks
from boring_tasks.lib import try_me

if __name__ == '__main__':
  print(try_me())
